#ifndef LOREMIPSUMTESTDATA_H
#define LOREMIPSUMTESTDATA_H

static const QString fiveHundredWordsLoremIpsumText = QStringLiteral("# Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n"
    "Sed vulputate viverra neque, ac tincidunt metus facilisis a. Morbi lobortis enim nisi, vitae pellentesque arcu pharetra in. " 
    "Duis ante purus, sodales et velit nec, varius convallis dolor. Fusce pharetra arcu velit, vel finibus nisl vulputate in. "
    "Nam ac tortor at tellus dapibus rutrum sed sit amet tortor. Donec sagittis enim vitae sem suscipit, sed sollicitudin justo ullamcorper. "
    "Praesent massa elit, faucibus id pulvinar sit amet, hendrerit nec sapien. Duis in quam non felis finibus finibus ultricies ut tortor. " 
    "Vestibulum lobortis tortor luctus imperdiet varius. Phasellus luctus nulla quis elit venenatis, at facilisis mi rhoncus.\n"
    "\n"
    "1. Vestibulum bibendum ante et lacinia auctor. Vivamus eu sodales sapien.\n"
    "2. Ut suscipit ipsum non venenatis mattis. Pellentesque rhoncus efficitur odio, ut malesuada sapien blandit in.\n"
    "3. Donec convallis sem et suscipit interdum. Integer interdum faucibus vestibulum.\n"
    "\n"
    "## Quisque nec magna placerat ligula molestie mollis.\n "
    "*Fusce* auctor sed quam sed suscipit. Praesent at neque dolor. "
    "Nunc rutrum aliquet eros, et rhoncus lacus fringilla eget. Vestibulum rhoncus eros quis vestibulum porttitor. "
    "Pellentesque blandit porta dui id ornare. Sed sed nulla nibh. Ut sed auctor sapien. "
    "Maecenas egestas ipsum in iaculis aliquet. Fusce sem ante, fringilla interdum cursus eget, vestibulum vel tellus. "
    "Phasellus tincidunt, erat in rhoncus faucibus, lacus magna facilisis felis, vel vehicula enim nisl ut sapien. Proin id elit at risus facilisis tristique. "
    "Nulla facilisi. Duis scelerisque, purus a dictum sagittis, magna augue mollis massa, et gravida nisl nunc eget dui.\n"
    "\n"
    "Suspendisse laoreet bibendum est et ornare. Phasellus elementum elit ac tincidunt ornare. "
    "Donec ac lacus leo. Cras rhoncus **accumsan** mauris, eget aliquam sapien pulvinar blandit. "
    "Proin sem justo, gravida et mi vitae, laoreet scelerisque sem. Cras sagittis justo a bibendum tempus. "
    "Maecenas ac lacus ultrices, congue mauris ut, euismod velit. Sed lorem nulla, posuere vitae cursus auctor, dignissim vel ligula. "
    "Integer pharetra ultricies neque vitae mollis.\n"
    "\n"
    "# Fusce in tincidunt lacus, a molestie sapien.\n "
    "Aliquam at accumsan eros. Pellentesque vulputate vehicula nibh, a facilisis nunc placerat at. "
    "`Praesent iaculis justo ut placerat laoreet`. Vestibulum et felis sed justo egestas tempor. "
    "Pellentesque pretium, arcu at pellentesque egestas, est ante dignissim ex, quis interdum velit justo at tellus. "
    "Nunc in mauris et velit luctus congue. Phasellus in augue elementum, ornare tellus a, vehicula dui. "
    "Integer leo ex, vestibulum rutrum mi ut, maximus consectetur dolor.\n"
    "\n"
    "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fringilla semper dui quis laoreet. "
    "Fusce hendrerit tincidunt eros, nec congue purus. Ut metus tortor, aliquet nec libero ac, porta pellentesque mi. "
    "Nam euismod vel neque at dignissim. Vivamus sapien nisi, bibendum vel libero in, suscipit eleifend erat. "
    "Curabitur vitae molestie orci. Aenean eros sem, volutpat id rutrum vitae, varius non mauris. "
    "Praesent blandit facilisis ex maximus blandit. Proin ut sapien orci. "
    "Curabitur commodo nibh mauris, a venenatis erat tristique sit amet. Fusce condimentum dui at risus laoreet, vel lobortis velit ultrices. "
    "Fusce tincidunt, ante congue dignissim iaculis, ante mauris fermentum mi, at aliquet lorem erat at ex. Mauris in purus eleifend, pharetra ante ac.\n"
    "\n");

#endif // LOREMIPSUMTESTDATA_H
